export type areaLifeKeys =
  | "ImportantPerson"
  | "Family"
  | "Friendship"
  | "PhysicalHealth"
  | "Spirituality"
  | "Community"
  | "SocialParticipation"
  | "Work"
  | "Education"
  | "Finances"
  | "Hobbies"
  | "OnlineEntertainment"
  | "OfflineEntertainment"
  | "PhysiologicalNeeds"
  | "ActivitiesOfDailyLiving";
